[project]
name = "diogenes-annotation-tool"
version = "0.1.0"
description = "A tool to assist with the creation of annotation files for the Diogenes pipeline"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas>=2.0.3",
    "scikit-learn>=1.3.2",
    "xlsxwriter>=3.2.3",
]
